# Intro to Plastic Emissions

Environmental preservation is an issue that has become increasingly important. We are seeing the detrimental effects pollution can have on our world, which brings us to the topic of plastics. Plastics are a huge fraction of landfills and often taking decades or longer to fully decompose which leads to even more build up. Despite changes beginning to be implemented, many large corporations still produce huge amounts of single use plastic that end up in the environment, potentially harming wildlife in the process. The #BreakFreeFromPlastic movement compiled data from many cleanup events, detailing the company each piece of plastic originated from. We pulled this data from the [TidyTuesday data repository on GitHub.](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-01-26/readme.md) Using this data we looked to answer questions like: Which companies are responsible for the most amounts of plastic found during the cleanups? How do the number of events and the number of volunteers compare in each country? Which types of plastic are most commonly found during these cleanups? Some things to be conscious of when analyzing this data are: Different standards for plastic disposal in different countries. Ability for certain countries to implement plastic alternatives compared to others, usually due to affordability. The size, population, and population density of different locations.
